import { OasExtensibleNode, IOasNodeVisitor } from 'oai-ts-core';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export type Parameter = ParameterWithSchema | ParameterWithContent;
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export type ParameterWithSchema = ParameterWithSchemaWithExample | ParameterWithSchemaWithExamples;
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export type ParameterWithSchemaWithExample =
  | ParameterWithSchemaWithExampleInPath
  | ParameterWithSchemaWithExampleInQuery
  | ParameterWithSchemaWithExampleInHeader
  | ParameterWithSchemaWithExampleInCookie;
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export type ParameterWithSchemaWithExamples =
  | ParameterWithSchemaWithExamplesInPath
  | ParameterWithSchemaWithExamplesInQuery
  | ParameterWithSchemaWithExamplesInHeader
  | ParameterWithSchemaWithExamplesInCookie;
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export type ParameterWithContent = ParameterWithContentInPath | ParameterWithContentNotInPath;
/**
 * Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.
 */
export type MediaType = MediaTypeWithExample | MediaTypeWithExamples;
/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export type Header = HeaderWithSchema | HeaderWithContent;
/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export type HeaderWithSchema = HeaderWithSchemaWithExample | HeaderWithSchemaWithExamples;
/**
 * The `Link Object` is responsible for defining a possible operation based on a single response.
 */
export type Link = LinkWithOperationRef | LinkWithOperationId;
/**
 * Allows the definition of a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header or as a query parameter) and OAuth2's common flows (implicit, password, application and access code).
 */
export type SecurityScheme =
  | ApiKeySecurityScheme
  | HttpSecurityScheme
  | OAuth2SecurityScheme
  | OpenIdConnectSecurityScheme;
export type HttpSecurityScheme = NonBearerHttpSecurityScheme | BearerHttpSecurityScheme;

/**
 * This is the root document object for the API specification. It combines what previously was the Resource Listing and API Declaration (version 1.2 and earlier) together into one document.
 */
export interface IOasOpenapi3 {
  openapi: string;
  info: Info;
  externalDocs?: ExternalDocumentation;
  servers?: Server[];
  security?: SecurityRequirement[];
  tags?: Tag[];
  paths: Paths;
  components?: Components;
  /**
   * This interface was referenced by `Openapi3`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This is the root document object for the API specification. It combines what previously was the Resource Listing and API Declaration (version 1.2 and earlier) together into one document.
 */
export class OasOpenapi3 extends OasExtensibleNode implements IOasOpenapi3 {
  openapi: string;
  info: Info;
  externalDocs?: ExternalDocumentation;
  servers?: Server[];
  security?: SecurityRequirement[];
  tags?: Tag[];
  paths: Paths;
  components?: Components;
  /**
   * This interface was referenced by `Openapi3`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasOpenapi3 object.
   * @return {OasOpenapi3}
   */
  public createOasOpenapi3(): IOasOpenapi3 {
    let rval: OasOpenapi3 = new OasOpenapi3();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitOpenapi3(<IOasOpenapi3>this);
  }
}

/**
 * The object provides metadata about the API. The metadata can be used by the clients if needed, and can be presented in editing or documentation generation tools for convenience.
 */
export interface IOasInfo {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: Contact;
  license?: License;
  version: string;
  /**
   * This interface was referenced by `Info`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  accept(visitor: IOasNodeVisitor);
}
/**
 * The object provides metadata about the API. The metadata can be used by the clients if needed, and can be presented in editing or documentation generation tools for convenience.
 */
export class OasInfo extends OasExtensibleNode implements IOasInfo {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: Contact;
  license?: License;
  version: string;
  /**
   * This interface was referenced by `Info`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasInfo object.
   * @return {OasInfo}
   */
  public createOasInfo(): IOasInfo {
    let rval: OasInfo = new OasInfo();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitInfo(<IOasInfo>this);
  }
}

/**
 * Contact information for the exposed API.
 */
export interface IOasContact {
  name?: string;
  url?: string;
  email?: string;
  /**
   * This interface was referenced by `Contact`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Contact information for the exposed API.
 */
export class OasContact extends OasExtensibleNode implements IOasContact {
  name?: string;
  url?: string;
  email?: string;
  /**
   * This interface was referenced by `Contact`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasContact object.
   * @return {OasContact}
   */
  public createOasContact(): IOasContact {
    let rval: OasContact = new OasContact();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitContact(<IOasContact>this);
  }
}

/**
 * License information for the exposed API.
 */
export interface IOasLicense {
  name: string;
  url?: string;
  /**
   * This interface was referenced by `License`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * License information for the exposed API.
 */
export class OasLicense extends OasExtensibleNode implements IOasLicense {
  name: string;
  url?: string;
  /**
   * This interface was referenced by `License`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasLicense object.
   * @return {OasLicense}
   */
  public createOasLicense(): IOasLicense {
    let rval: OasLicense = new OasLicense();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitLicense(<IOasLicense>this);
  }
}

/**
 * Allows referencing an external resource for extended documentation.
 */
export interface IOasExternalDocumentation {
  description?: string;
  url: string;
  /**
   * This interface was referenced by `ExternalDocumentation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Allows referencing an external resource for extended documentation.
 */
export class OasExternalDocumentation extends OasExtensibleNode implements IOasExternalDocumentation {
  description?: string;
  url: string;
  /**
   * This interface was referenced by `ExternalDocumentation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasExternalDocumentation object.
   * @return {OasExternalDocumentation}
   */
  public createOasExternalDocumentation(): IOasExternalDocumentation {
    let rval: OasExternalDocumentation = new OasExternalDocumentation();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitExternalDocumentation(<IOasExternalDocumentation>this);
  }
}

/**
 * An object representing a Server.
 */
export interface IOasServer {
  url: string;
  description?: string;
  variables?: {
    [k: string]: ServerVariable;
  };
  /**
   * This interface was referenced by `Server`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * An object representing a Server.
 */
export class OasServer extends OasExtensibleNode implements IOasServer {
  url: string;
  description?: string;
  variables?: {
    [k: string]: ServerVariable;
  };
  /**
   * This interface was referenced by `Server`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasServer object.
   * @return {OasServer}
   */
  public createOasServer(): IOasServer {
    let rval: OasServer = new OasServer();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitServer(<IOasServer>this);
  }
}

/**
 * An object representing a Server Variable for server URL template substitution.
 */
export interface IOasServerVariable {
  enum?: string[];
  default: string;
  description?: string;
  /**
   * This interface was referenced by `ServerVariable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * An object representing a Server Variable for server URL template substitution.
 */
export class OasServerVariable extends OasExtensibleNode implements IOasServerVariable {
  enum?: string[];
  default: string;
  description?: string;
  /**
   * This interface was referenced by `ServerVariable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasServerVariable object.
   * @return {OasServerVariable}
   */
  public createOasServerVariable(): IOasServerVariable {
    let rval: OasServerVariable = new OasServerVariable();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitServerVariable(<IOasServerVariable>this);
  }
}

/**
 * Lists the required security schemes to execute this operation. The name used for each property MUST correspond to a security scheme declared in the Security Schemes under the Components Object.  Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where there multiple query parameters or HTTP headers are required to convey security information.  When a list of Security Requirement Objects is defined on the Open API object or Operation Object, only one of Security Requirement Objects in the list needs to be satisfied to authorize.
 */
export interface IOasSecurityRequirement {
  [k: string]: string[];
}
/**
 * Lists the required security schemes to execute this operation. The name used for each property MUST correspond to a security scheme declared in the Security Schemes under the Components Object.  Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where there multiple query parameters or HTTP headers are required to convey security information.  When a list of Security Requirement Objects is defined on the Open API object or Operation Object, only one of Security Requirement Objects in the list needs to be satisfied to authorize.
 */
export class OasSecurityRequirement extends OasExtensibleNode implements IOasSecurityRequirement {
  [k: string]: string[];

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasSecurityRequirement object.
   * @return {OasSecurityRequirement}
   */
  public createOasSecurityRequirement(): IOasSecurityRequirement {
    let rval: OasSecurityRequirement = new OasSecurityRequirement();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitSecurityRequirement(<IOasSecurityRequirement>this);
  }
}

/**
 * Allows adding meta data to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag used there.
 */
export interface IOasTag {
  name: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  /**
   * This interface was referenced by `Tag`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Allows adding meta data to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag used there.
 */
export class OasTag extends OasExtensibleNode implements IOasTag {
  name: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  /**
   * This interface was referenced by `Tag`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasTag object.
   * @return {OasTag}
   */
  public createOasTag(): IOasTag {
    let rval: OasTag = new OasTag();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitTag(<IOasTag>this);
  }
}

/**
 * Holds the relative paths to the individual endpoints and their operations. The path is appended to the URL from the `Server Object` in order to construct the full URL.  The Paths MAY be empty, due to ACL constraints.
 */
export interface IOasPaths {}
/**
 * Holds the relative paths to the individual endpoints and their operations. The path is appended to the URL from the `Server Object` in order to construct the full URL.  The Paths MAY be empty, due to ACL constraints.
 */
export class OasPaths extends OasExtensibleNode implements IOasPaths {
  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasPaths object.
   * @return {OasPaths}
   */
  public createOasPaths(): IOasPaths {
    let rval: OasPaths = new OasPaths();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitPaths(<IOasPaths>this);
  }
}

/**
 * Describes the operations available on a single path. A Path Item MAY be empty, due to ACL constraints. The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available.
 *
 * This interface was referenced by `Paths`'s JSON-Schema definition
 * via the `patternProperty` "^\/".
 */
export interface IOasPathItem {
  $ref?: string;
  summary?: string;
  description?: string;
  get?: Operation;
  put?: Operation;
  post?: Operation;
  delete?: Operation;
  options?: Operation;
  head?: Operation;
  patch?: Operation;
  trace?: Operation;
  servers?: Server[];
  parameters?: (Parameter | Reference)[];
  /**
   * This interface was referenced by `PathItem`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes the operations available on a single path. A Path Item MAY be empty, due to ACL constraints. The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available.
 *
 * This interface was referenced by `Paths`'s JSON-Schema definition
 * via the `patternProperty` "^\/".
 */
export class OasPathItem extends OasExtensibleNode implements IOasPathItem {
  $ref?: string;
  summary?: string;
  description?: string;
  get?: Operation;
  put?: Operation;
  post?: Operation;
  delete?: Operation;
  options?: Operation;
  head?: Operation;
  patch?: Operation;
  trace?: Operation;
  servers?: Server[];
  parameters?: (Parameter | Reference)[];
  /**
   * This interface was referenced by `PathItem`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasPathItem object.
   * @return {OasPathItem}
   */
  public createOasPathItem(): IOasPathItem {
    let rval: OasPathItem = new OasPathItem();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitPathItem(<IOasPathItem>this);
  }
}

/**
 * Describes a single API operation on a path.
 */
export interface IOasOperation {
  tags?: string[];
  summary?: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  operationId?: string;
  parameters?: (Parameter | Reference)[];
  requestBody?: RequestBody | Reference;
  responses: Responses;
  callbacks?: {
    [k: string]: Callback | Reference;
  };
  deprecated?: boolean;
  security?: SecurityRequirement[];
  servers?: Server[];
  /**
   * This interface was referenced by `Operation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single API operation on a path.
 */
export class OasOperation extends OasExtensibleNode implements IOasOperation {
  tags?: string[];
  summary?: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  operationId?: string;
  parameters?: (Parameter | Reference)[];
  requestBody?: RequestBody | Reference;
  responses: Responses;
  callbacks?: {
    [k: string]: Callback | Reference;
  };
  deprecated?: boolean;
  security?: SecurityRequirement[];
  servers?: Server[];
  /**
   * This interface was referenced by `Operation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasOperation object.
   * @return {OasOperation}
   */
  public createOasOperation(): IOasOperation {
    let rval: OasOperation = new OasOperation();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitOperation(<IOasOperation>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExampleInPath {
  name: string;
  in: "path";
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "matrix" | "label" | "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExampleInPath extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExampleInPath {
  name: string;
  in: "path";
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "matrix" | "label" | "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExampleInPath object.
   * @return {OasParameterWithSchemaWithExampleInPath}
   */
  public createOasParameterWithSchemaWithExampleInPath(): IOasParameterWithSchemaWithExampleInPath {
    let rval: OasParameterWithSchemaWithExampleInPath = new OasParameterWithSchemaWithExampleInPath();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExampleInPath(<IOasParameterWithSchemaWithExampleInPath>this);
  }
}

/**
 * The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is an extended subset of the JSON Schema Specification Wright Draft 00.  Further information about the properties can be found in JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema specification as referenced here.
 */
export interface IOasSchema {
  title?: string;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: number;
  minLength?: number;
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  uniqueItems?: boolean;
  maxProperties?: number;
  minProperties?: number;
  required?: string[];
  enum?: any[];
  type?: "array" | "boolean" | "integer" | "number" | "object" | "string";
  not?: Schema | Reference;
  allOf?: (Schema | Reference)[];
  oneOf?: (Schema | Reference)[];
  anyOf?: (Schema | Reference)[];
  items?: Schema | Reference;
  properties?: {
    [k: string]: Schema | Reference;
  };
  additionalProperties?: Schema | Reference | boolean;
  description?: string;
  format?: string;
  default?: any;
  nullable?: boolean;
  discriminator?: Discriminator;
  readOnly?: boolean;
  writeOnly?: boolean;
  example?: any;
  externalDocs?: ExternalDocumentation;
  deprecated?: boolean;
  xml?: Xml;
  /**
   * This interface was referenced by `Schema`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is an extended subset of the JSON Schema Specification Wright Draft 00.  Further information about the properties can be found in JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema specification as referenced here.
 */
export class OasSchema extends OasExtensibleNode implements IOasSchema {
  title?: string;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: number;
  minLength?: number;
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  uniqueItems?: boolean;
  maxProperties?: number;
  minProperties?: number;
  required?: string[];
  enum?: any[];
  type?: "array" | "boolean" | "integer" | "number" | "object" | "string";
  not?: Schema | Reference;
  allOf?: (Schema | Reference)[];
  oneOf?: (Schema | Reference)[];
  anyOf?: (Schema | Reference)[];
  items?: Schema | Reference;
  properties?: {
    [k: string]: Schema | Reference;
  };
  additionalProperties?: Schema | Reference | boolean;
  description?: string;
  format?: string;
  default?: any;
  nullable?: boolean;
  discriminator?: Discriminator;
  readOnly?: boolean;
  writeOnly?: boolean;
  example?: any;
  externalDocs?: ExternalDocumentation;
  deprecated?: boolean;
  xml?: Xml;
  /**
   * This interface was referenced by `Schema`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasSchema object.
   * @return {OasSchema}
   */
  public createOasSchema(): IOasSchema {
    let rval: OasSchema = new OasSchema();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitSchema(<IOasSchema>this);
  }
}

/**
 * A simple object to allow referencing other components in the specification, internally and externally.  The Reference Object is defined by JSON Reference and follows the same structure, behavior and rules.   For this specification, reference resolution is done as defined by the JSON Reference specification and not by the JSON Schema specification.
 */
export interface IOasReference {
  $ref: string;
  [k: string]: any;
}
/**
 * A simple object to allow referencing other components in the specification, internally and externally.  The Reference Object is defined by JSON Reference and follows the same structure, behavior and rules.   For this specification, reference resolution is done as defined by the JSON Reference specification and not by the JSON Schema specification.
 */
export class OasReference extends OasExtensibleNode implements IOasReference {
  $ref: string;
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasReference object.
   * @return {OasReference}
   */
  public createOasReference(): IOasReference {
    let rval: OasReference = new OasReference();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitReference(<IOasReference>this);
  }
}

/**
 * When request bodies or response payloads may be one of a number of different schemas, a `discriminator` object can be used to aid in serialization, deserialization, and validation.  The discriminator is a specific object in a schema which is used to inform the consumer of the specification of an alternative schema based on the value associated with it.  Note, when using the discriminator, _inline_ schemas will not be considered when using the discriminator.
 */
export interface IOasDiscriminator {
  propertyName: string;
  mapping?: {
    [k: string]: string;
  };
  [k: string]: any;
}
/**
 * When request bodies or response payloads may be one of a number of different schemas, a `discriminator` object can be used to aid in serialization, deserialization, and validation.  The discriminator is a specific object in a schema which is used to inform the consumer of the specification of an alternative schema based on the value associated with it.  Note, when using the discriminator, _inline_ schemas will not be considered when using the discriminator.
 */
export class OasDiscriminator extends OasExtensibleNode implements IOasDiscriminator {
  propertyName: string;
  mapping?: {
    [k: string]: string;
  };
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasDiscriminator object.
   * @return {OasDiscriminator}
   */
  public createOasDiscriminator(): IOasDiscriminator {
    let rval: OasDiscriminator = new OasDiscriminator();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitDiscriminator(<IOasDiscriminator>this);
  }
}

/**
 * A metadata object that allows for more fine-tuned XML model definitions.  When using arrays, XML element names are *not* inferred (for singular/plural forms) and the `name` property SHOULD be used to add that information. See examples for expected behavior.
 */
export interface IOasXml {
  name?: string;
  namespace?: string;
  prefix?: string;
  attribute?: boolean;
  wrapped?: boolean;
  /**
   * This interface was referenced by `Xml`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * A metadata object that allows for more fine-tuned XML model definitions.  When using arrays, XML element names are *not* inferred (for singular/plural forms) and the `name` property SHOULD be used to add that information. See examples for expected behavior.
 */
export class OasXml extends OasExtensibleNode implements IOasXml {
  name?: string;
  namespace?: string;
  prefix?: string;
  attribute?: boolean;
  wrapped?: boolean;
  /**
   * This interface was referenced by `Xml`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasXml object.
   * @return {OasXml}
   */
  public createOasXml(): IOasXml {
    let rval: OasXml = new OasXml();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitXml(<IOasXml>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExampleInQuery {
  name: string;
  in: "query";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExampleInQuery extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExampleInQuery {
  name: string;
  in: "query";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExampleInQuery object.
   * @return {OasParameterWithSchemaWithExampleInQuery}
   */
  public createOasParameterWithSchemaWithExampleInQuery(): IOasParameterWithSchemaWithExampleInQuery {
    let rval: OasParameterWithSchemaWithExampleInQuery = new OasParameterWithSchemaWithExampleInQuery();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExampleInQuery(<IOasParameterWithSchemaWithExampleInQuery>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExampleInHeader {
  name: string;
  in: "header";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExampleInHeader extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExampleInHeader {
  name: string;
  in: "header";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExampleInHeader object.
   * @return {OasParameterWithSchemaWithExampleInHeader}
   */
  public createOasParameterWithSchemaWithExampleInHeader(): IOasParameterWithSchemaWithExampleInHeader {
    let rval: OasParameterWithSchemaWithExampleInHeader = new OasParameterWithSchemaWithExampleInHeader();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExampleInHeader(<IOasParameterWithSchemaWithExampleInHeader>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExampleInCookie {
  name: string;
  in: "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExampleInCookie extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExampleInCookie {
  name: string;
  in: "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExampleInCookie object.
   * @return {OasParameterWithSchemaWithExampleInCookie}
   */
  public createOasParameterWithSchemaWithExampleInCookie(): IOasParameterWithSchemaWithExampleInCookie {
    let rval: OasParameterWithSchemaWithExampleInCookie = new OasParameterWithSchemaWithExampleInCookie();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExampleInCookie(<IOasParameterWithSchemaWithExampleInCookie>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExamplesInPath {
  name: string;
  in: "path";
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "matrix" | "label" | "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExamplesInPath extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExamplesInPath {
  name: string;
  in: "path";
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "matrix" | "label" | "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExamplesInPath object.
   * @return {OasParameterWithSchemaWithExamplesInPath}
   */
  public createOasParameterWithSchemaWithExamplesInPath(): IOasParameterWithSchemaWithExamplesInPath {
    let rval: OasParameterWithSchemaWithExamplesInPath = new OasParameterWithSchemaWithExamplesInPath();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExamplesInPath(<IOasParameterWithSchemaWithExamplesInPath>this);
  }
}

export interface IOasExample {
  summary?: string;
  description?: string;
  value?: any;
  externalValue?: string;
  /**
   * This interface was referenced by `Example`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasExample extends OasExtensibleNode implements IOasExample {
  summary?: string;
  description?: string;
  value?: any;
  externalValue?: string;
  /**
   * This interface was referenced by `Example`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasExample object.
   * @return {OasExample}
   */
  public createOasExample(): IOasExample {
    let rval: OasExample = new OasExample();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitExample(<IOasExample>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExamplesInQuery {
  name: string;
  in: "query";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExamplesInQuery extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExamplesInQuery {
  name: string;
  in: "query";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExamplesInQuery object.
   * @return {OasParameterWithSchemaWithExamplesInQuery}
   */
  public createOasParameterWithSchemaWithExamplesInQuery(): IOasParameterWithSchemaWithExamplesInQuery {
    let rval: OasParameterWithSchemaWithExamplesInQuery = new OasParameterWithSchemaWithExamplesInQuery();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExamplesInQuery(<IOasParameterWithSchemaWithExamplesInQuery>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExamplesInHeader {
  name: string;
  in: "header";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExamplesInHeader extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExamplesInHeader {
  name: string;
  in: "header";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExamplesInHeader object.
   * @return {OasParameterWithSchemaWithExamplesInHeader}
   */
  public createOasParameterWithSchemaWithExamplesInHeader(): IOasParameterWithSchemaWithExamplesInHeader {
    let rval: OasParameterWithSchemaWithExamplesInHeader = new OasParameterWithSchemaWithExamplesInHeader();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExamplesInHeader(<IOasParameterWithSchemaWithExamplesInHeader>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithSchemaWithExamplesInCookie {
  name: string;
  in: "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithSchemaWithExamplesInCookie extends OasExtensibleNode
  implements IOasParameterWithSchemaWithExamplesInCookie {
  name: string;
  in: "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "form";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithSchemaWithExamplesInCookie object.
   * @return {OasParameterWithSchemaWithExamplesInCookie}
   */
  public createOasParameterWithSchemaWithExamplesInCookie(): IOasParameterWithSchemaWithExamplesInCookie {
    let rval: OasParameterWithSchemaWithExamplesInCookie = new OasParameterWithSchemaWithExamplesInCookie();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithSchemaWithExamplesInCookie(<IOasParameterWithSchemaWithExamplesInCookie>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithContentInPath {
  name: string;
  in: "path";
  description?: string;
  required?: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithContentInPath extends OasExtensibleNode implements IOasParameterWithContentInPath {
  name: string;
  in: "path";
  description?: string;
  required?: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithContentInPath object.
   * @return {OasParameterWithContentInPath}
   */
  public createOasParameterWithContentInPath(): IOasParameterWithContentInPath {
    let rval: OasParameterWithContentInPath = new OasParameterWithContentInPath();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithContentInPath(<IOasParameterWithContentInPath>this);
  }
}

/**
 * Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.
 */
export interface IOasMediaTypeWithExample {
  schema?: Schema | Reference;
  example?: any;
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.
 */
export class OasMediaTypeWithExample extends OasExtensibleNode implements IOasMediaTypeWithExample {
  schema?: Schema | Reference;
  example?: any;
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasMediaTypeWithExample object.
   * @return {OasMediaTypeWithExample}
   */
  public createOasMediaTypeWithExample(): IOasMediaTypeWithExample {
    let rval: OasMediaTypeWithExample = new OasMediaTypeWithExample();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitMediaTypeWithExample(<IOasMediaTypeWithExample>this);
  }
}

/**
 * An object representing multipart region encoding for `requestBody` objects.
 */
export interface IOasEncoding {
  contentType?: string;
  headers?: {
    [k: string]: Header;
  };
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
}
/**
 * An object representing multipart region encoding for `requestBody` objects.
 */
export class OasEncoding extends OasExtensibleNode implements IOasEncoding {
  contentType?: string;
  headers?: {
    [k: string]: Header;
  };
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasEncoding object.
   * @return {OasEncoding}
   */
  public createOasEncoding(): IOasEncoding {
    let rval: OasEncoding = new OasEncoding();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitEncoding(<IOasEncoding>this);
  }
}

/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export interface IOasHeaderWithSchemaWithExample {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `HeaderWithSchemaWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export class OasHeaderWithSchemaWithExample extends OasExtensibleNode implements IOasHeaderWithSchemaWithExample {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `HeaderWithSchemaWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasHeaderWithSchemaWithExample object.
   * @return {OasHeaderWithSchemaWithExample}
   */
  public createOasHeaderWithSchemaWithExample(): IOasHeaderWithSchemaWithExample {
    let rval: OasHeaderWithSchemaWithExample = new OasHeaderWithSchemaWithExample();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitHeaderWithSchemaWithExample(<IOasHeaderWithSchemaWithExample>this);
  }
}

/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export interface IOasHeaderWithSchemaWithExamples {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `HeaderWithSchemaWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export class OasHeaderWithSchemaWithExamples extends OasExtensibleNode implements IOasHeaderWithSchemaWithExamples {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: "simple";
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `HeaderWithSchemaWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasHeaderWithSchemaWithExamples object.
   * @return {OasHeaderWithSchemaWithExamples}
   */
  public createOasHeaderWithSchemaWithExamples(): IOasHeaderWithSchemaWithExamples {
    let rval: OasHeaderWithSchemaWithExamples = new OasHeaderWithSchemaWithExamples();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitHeaderWithSchemaWithExamples(<IOasHeaderWithSchemaWithExamples>this);
  }
}

/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export interface IOasHeaderWithContent {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `HeaderWithContent`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The Header Object follows the structure of the Parameter Object, with the following changes:  1. `name` MUST NOT be specified, it is given in the Headers Object. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`).
 */
export class OasHeaderWithContent extends OasExtensibleNode implements IOasHeaderWithContent {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `HeaderWithContent`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasHeaderWithContent object.
   * @return {OasHeaderWithContent}
   */
  public createOasHeaderWithContent(): IOasHeaderWithContent {
    let rval: OasHeaderWithContent = new OasHeaderWithContent();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitHeaderWithContent(<IOasHeaderWithContent>this);
  }
}

/**
 * Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.
 */
export interface IOasMediaTypeWithExamples {
  schema?: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.
 */
export class OasMediaTypeWithExamples extends OasExtensibleNode implements IOasMediaTypeWithExamples {
  schema?: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasMediaTypeWithExamples object.
   * @return {OasMediaTypeWithExamples}
   */
  public createOasMediaTypeWithExamples(): IOasMediaTypeWithExamples {
    let rval: OasMediaTypeWithExamples = new OasMediaTypeWithExamples();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitMediaTypeWithExamples(<IOasMediaTypeWithExamples>this);
  }
}

/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export interface IOasParameterWithContentNotInPath {
  name: string;
  in: "query" | "header" | "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentNotInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location.
 */
export class OasParameterWithContentNotInPath extends OasExtensibleNode implements IOasParameterWithContentNotInPath {
  name: string;
  in: "query" | "header" | "cookie";
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentNotInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasParameterWithContentNotInPath object.
   * @return {OasParameterWithContentNotInPath}
   */
  public createOasParameterWithContentNotInPath(): IOasParameterWithContentNotInPath {
    let rval: OasParameterWithContentNotInPath = new OasParameterWithContentNotInPath();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitParameterWithContentNotInPath(<IOasParameterWithContentNotInPath>this);
  }
}

/**
 * Describes a single request body.
 */
export interface IOasRequestBody {
  description?: string;
  content: {
    [k: string]: MediaType;
  };
  required?: boolean;
  /**
   * This interface was referenced by `RequestBody`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single request body.
 */
export class OasRequestBody extends OasExtensibleNode implements IOasRequestBody {
  description?: string;
  content: {
    [k: string]: MediaType;
  };
  required?: boolean;
  /**
   * This interface was referenced by `RequestBody`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasRequestBody object.
   * @return {OasRequestBody}
   */
  public createOasRequestBody(): IOasRequestBody {
    let rval: OasRequestBody = new OasRequestBody();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitRequestBody(<IOasRequestBody>this);
  }
}

/**
 * A container for the expected responses of an operation. The container maps a HTTP response code to the expected response.  It is not expected for the documentation to necessarily cover all possible HTTP response codes, since they may not be known in advance. However, it is expected for the documentation to cover a successful operation response and any known errors.  The `default` MAY be used as a default response object for all HTTP codes  that are not covered individually by the specification.  The `Responses Object` MUST contain at least one response code, and it  SHOULD be the response for a successful operation call.
 */
export interface IOasResponses {
  default?: Response | Reference;
}
/**
 * A container for the expected responses of an operation. The container maps a HTTP response code to the expected response.  It is not expected for the documentation to necessarily cover all possible HTTP response codes, since they may not be known in advance. However, it is expected for the documentation to cover a successful operation response and any known errors.  The `default` MAY be used as a default response object for all HTTP codes  that are not covered individually by the specification.  The `Responses Object` MUST contain at least one response code, and it  SHOULD be the response for a successful operation call.
 */
export class OasResponses extends OasExtensibleNode implements IOasResponses {
  default?: Response | Reference;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasResponses object.
   * @return {OasResponses}
   */
  public createOasResponses(): IOasResponses {
    let rval: OasResponses = new OasResponses();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitResponses(<IOasResponses>this);
  }
}

/**
 * Describes a single response from an API Operation, including design-time, static  `links` to operations based on the response.
 */
export interface IOasResponse {
  description: string;
  headers?: {
    [k: string]: Header | Reference;
  };
  content?: {
    [k: string]: MediaType;
  };
  links?: {
    [k: string]: Link | Reference;
  };
  /**
   * This interface was referenced by `Response`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Describes a single response from an API Operation, including design-time, static  `links` to operations based on the response.
 */
export class OasResponse extends OasExtensibleNode implements IOasResponse {
  description: string;
  headers?: {
    [k: string]: Header | Reference;
  };
  content?: {
    [k: string]: MediaType;
  };
  links?: {
    [k: string]: Link | Reference;
  };
  /**
   * This interface was referenced by `Response`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasResponse object.
   * @return {OasResponse}
   */
  public createOasResponse(): IOasResponse {
    let rval: OasResponse = new OasResponse();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitResponse(<IOasResponse>this);
  }
}

/**
 * The `Link Object` is responsible for defining a possible operation based on a single response.
 */
export interface IOasLinkWithOperationRef {
  operationRef?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationRef`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The `Link Object` is responsible for defining a possible operation based on a single response.
 */
export class OasLinkWithOperationRef extends OasExtensibleNode implements IOasLinkWithOperationRef {
  operationRef?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationRef`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasLinkWithOperationRef object.
   * @return {OasLinkWithOperationRef}
   */
  public createOasLinkWithOperationRef(): IOasLinkWithOperationRef {
    let rval: OasLinkWithOperationRef = new OasLinkWithOperationRef();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitLinkWithOperationRef(<IOasLinkWithOperationRef>this);
  }
}

/**
 * The `Link Object` is responsible for defining a possible operation based on a single response.
 */
export interface IOasLinkWithOperationId {
  operationId?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationId`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * The `Link Object` is responsible for defining a possible operation based on a single response.
 */
export class OasLinkWithOperationId extends OasExtensibleNode implements IOasLinkWithOperationId {
  operationId?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationId`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasLinkWithOperationId object.
   * @return {OasLinkWithOperationId}
   */
  public createOasLinkWithOperationId(): IOasLinkWithOperationId {
    let rval: OasLinkWithOperationId = new OasLinkWithOperationId();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitLinkWithOperationId(<IOasLinkWithOperationId>this);
  }
}

/**
 * A map of possible out-of band callbacks related to the parent operation. Each value in the map is a Path Item Object that describes a set of requests that may be initiated by the API provider and the expected responses. The key value used to identify the callback object is an expression, evaluated at runtime, that identifies a URL to use for the callback operation.
 */
export interface IOasCallback {
  [k: string]: PathItem;
}
/**
 * A map of possible out-of band callbacks related to the parent operation. Each value in the map is a Path Item Object that describes a set of requests that may be initiated by the API provider and the expected responses. The key value used to identify the callback object is an expression, evaluated at runtime, that identifies a URL to use for the callback operation.
 */
export class OasCallback extends OasExtensibleNode implements IOasCallback {
  [k: string]: PathItem;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasCallback object.
   * @return {OasCallback}
   */
  public createOasCallback(): IOasCallback {
    let rval: OasCallback = new OasCallback();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitCallback(<IOasCallback>this);
  }
}

/**
 * Holds a set of reusable objects for different aspects of the OAS. All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.
 */
export interface IOasComponents {
  schemas?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Schema;
  };
  responses?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Response;
  };
  parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Parameter;
  };
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Example;
  };
  requestBodies?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | RequestBody;
  };
  headers?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Header;
  };
  securitySchemes?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | SecurityScheme;
  };
  links?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Link;
  };
  callbacks?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Callback;
  };
  /**
   * This interface was referenced by `Components`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Holds a set of reusable objects for different aspects of the OAS. All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.
 */
export class OasComponents extends OasExtensibleNode implements IOasComponents {
  schemas?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Schema;
  };
  responses?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Response;
  };
  parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Parameter;
  };
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Example;
  };
  requestBodies?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | RequestBody;
  };
  headers?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Header;
  };
  securitySchemes?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | SecurityScheme;
  };
  links?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Link;
  };
  callbacks?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Callback;
  };
  /**
   * This interface was referenced by `Components`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasComponents object.
   * @return {OasComponents}
   */
  public createOasComponents(): IOasComponents {
    let rval: OasComponents = new OasComponents();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitComponents(<IOasComponents>this);
  }
}

export interface IOasApiKeySecurityScheme {
  type: "apiKey";
  name: string;
  in: "header" | "query" | "cookie";
  description?: string;
  /**
   * This interface was referenced by `ApiKeySecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasApiKeySecurityScheme extends OasExtensibleNode implements IOasApiKeySecurityScheme {
  type: "apiKey";
  name: string;
  in: "header" | "query" | "cookie";
  description?: string;
  /**
   * This interface was referenced by `ApiKeySecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasApiKeySecurityScheme object.
   * @return {OasApiKeySecurityScheme}
   */
  public createOasApiKeySecurityScheme(): IOasApiKeySecurityScheme {
    let rval: OasApiKeySecurityScheme = new OasApiKeySecurityScheme();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitApiKeySecurityScheme(<IOasApiKeySecurityScheme>this);
  }
}

export interface IOasNonBearerHttpSecurityScheme {
  scheme: string;
  description?: string;
  type: "http";
  /**
   * This interface was referenced by `NonBearerHttpSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasNonBearerHttpSecurityScheme extends OasExtensibleNode implements IOasNonBearerHttpSecurityScheme {
  scheme: string;
  description?: string;
  type: "http";
  /**
   * This interface was referenced by `NonBearerHttpSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasNonBearerHttpSecurityScheme object.
   * @return {OasNonBearerHttpSecurityScheme}
   */
  public createOasNonBearerHttpSecurityScheme(): IOasNonBearerHttpSecurityScheme {
    let rval: OasNonBearerHttpSecurityScheme = new OasNonBearerHttpSecurityScheme();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitNonBearerHttpSecurityScheme(<IOasNonBearerHttpSecurityScheme>this);
  }
}

export interface IOasBearerHttpSecurityScheme {
  scheme: "bearer";
  bearerFormat?: string;
  type: "http";
  description?: string;
  /**
   * This interface was referenced by `BearerHttpSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasBearerHttpSecurityScheme extends OasExtensibleNode implements IOasBearerHttpSecurityScheme {
  scheme: "bearer";
  bearerFormat?: string;
  type: "http";
  description?: string;
  /**
   * This interface was referenced by `BearerHttpSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasBearerHttpSecurityScheme object.
   * @return {OasBearerHttpSecurityScheme}
   */
  public createOasBearerHttpSecurityScheme(): IOasBearerHttpSecurityScheme {
    let rval: OasBearerHttpSecurityScheme = new OasBearerHttpSecurityScheme();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitBearerHttpSecurityScheme(<IOasBearerHttpSecurityScheme>this);
  }
}

export interface IOasOAuth2SecurityScheme {
  type: "oauth2";
  flows: OAuthFlows;
  description?: string;
  /**
   * This interface was referenced by `OAuth2SecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasOAuth2SecurityScheme extends OasExtensibleNode implements IOasOAuth2SecurityScheme {
  type: "oauth2";
  flows: OAuthFlows;
  description?: string;
  /**
   * This interface was referenced by `OAuth2SecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasOAuth2SecurityScheme object.
   * @return {OasOAuth2SecurityScheme}
   */
  public createOasOAuth2SecurityScheme(): IOasOAuth2SecurityScheme {
    let rval: OasOAuth2SecurityScheme = new OasOAuth2SecurityScheme();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitOAuth2SecurityScheme(<IOasOAuth2SecurityScheme>this);
  }
}

/**
 * Allows configuration of the supported OAuth Flows.
 */
export interface IOasOAuthFlows {
  implicit?: ImplicitOAuthFlow;
  password?: PasswordOAuthFlow;
  clientCredentials?: ClientCredentialsFlow;
  authorizationCode?: AuthorizationCodeOAuthFlow;
  /**
   * This interface was referenced by `OAuthFlows`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * Allows configuration of the supported OAuth Flows.
 */
export class OasOAuthFlows extends OasExtensibleNode implements IOasOAuthFlows {
  implicit?: ImplicitOAuthFlow;
  password?: PasswordOAuthFlow;
  clientCredentials?: ClientCredentialsFlow;
  authorizationCode?: AuthorizationCodeOAuthFlow;
  /**
   * This interface was referenced by `OAuthFlows`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasOAuthFlows object.
   * @return {OasOAuthFlows}
   */
  public createOasOAuthFlows(): IOasOAuthFlows {
    let rval: OasOAuthFlows = new OasOAuthFlows();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitOAuthFlows(<IOasOAuthFlows>this);
  }
}

export interface IOasImplicitOAuthFlow {
  authorizationUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ImplicitOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasImplicitOAuthFlow extends OasExtensibleNode implements IOasImplicitOAuthFlow {
  authorizationUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ImplicitOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasImplicitOAuthFlow object.
   * @return {OasImplicitOAuthFlow}
   */
  public createOasImplicitOAuthFlow(): IOasImplicitOAuthFlow {
    let rval: OasImplicitOAuthFlow = new OasImplicitOAuthFlow();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitImplicitOAuthFlow(<IOasImplicitOAuthFlow>this);
  }
}

export interface IOasPasswordOAuthFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `PasswordOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasPasswordOAuthFlow extends OasExtensibleNode implements IOasPasswordOAuthFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `PasswordOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasPasswordOAuthFlow object.
   * @return {OasPasswordOAuthFlow}
   */
  public createOasPasswordOAuthFlow(): IOasPasswordOAuthFlow {
    let rval: OasPasswordOAuthFlow = new OasPasswordOAuthFlow();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitPasswordOAuthFlow(<IOasPasswordOAuthFlow>this);
  }
}

export interface IOasClientCredentialsFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ClientCredentialsFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasClientCredentialsFlow extends OasExtensibleNode implements IOasClientCredentialsFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ClientCredentialsFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasClientCredentialsFlow object.
   * @return {OasClientCredentialsFlow}
   */
  public createOasClientCredentialsFlow(): IOasClientCredentialsFlow {
    let rval: OasClientCredentialsFlow = new OasClientCredentialsFlow();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitClientCredentialsFlow(<IOasClientCredentialsFlow>this);
  }
}

export interface IOasAuthorizationCodeOAuthFlow {
  authorizationUrl: string;
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `AuthorizationCodeOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasAuthorizationCodeOAuthFlow extends OasExtensibleNode implements IOasAuthorizationCodeOAuthFlow {
  authorizationUrl: string;
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `AuthorizationCodeOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasAuthorizationCodeOAuthFlow object.
   * @return {OasAuthorizationCodeOAuthFlow}
   */
  public createOasAuthorizationCodeOAuthFlow(): IOasAuthorizationCodeOAuthFlow {
    let rval: OasAuthorizationCodeOAuthFlow = new OasAuthorizationCodeOAuthFlow();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitAuthorizationCodeOAuthFlow(<IOasAuthorizationCodeOAuthFlow>this);
  }
}

export interface IOasOpenIdConnectSecurityScheme {
  type: "openIdConnect";
  openIdConnectUrl: string;
  description?: string;
  /**
   * This interface was referenced by `OpenIdConnectSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
export class OasOpenIdConnectSecurityScheme extends OasExtensibleNode implements IOasOpenIdConnectSecurityScheme {
  type: "openIdConnect";
  openIdConnectUrl: string;
  description?: string;
  /**
   * This interface was referenced by `OpenIdConnectSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;

  constructor() {
    super();
    this._ownerDocument = this;
  }
  /**
   * Creates an OAS 3.0 OasOpenIdConnectSecurityScheme object.
   * @return {OasOpenIdConnectSecurityScheme}
   */
  public createOasOpenIdConnectSecurityScheme(): IOasOpenIdConnectSecurityScheme {
    let rval: OasOpenIdConnectSecurityScheme = new OasOpenIdConnectSecurityScheme();
    rval._ownerDocument = this._ownerDocument;
    rval._parent = this;
    return rval;
  }

  /**
   * Accepts the given OAS node visitor and calls the appropriate method on it to visit this node.
   * @param visitor
   */
  public accept(visitor: IOasNodeVisitor): void {
    visitor.visitOpenIdConnectSecurityScheme(<IOasOpenIdConnectSecurityScheme>this);
  }
}
